//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Microservices.MultiplayerMicroservice"/> </summary
    public sealed class MultiplayerMicroserviceClient : MicroserviceClient, Beamable.Common.IHaveServiceName
    {
        
        public MultiplayerMicroserviceClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        public string ServiceName
        {
            get
            {
                return "MultiplayerMicroservice";
            }
        }
        
        /// <summary>
        /// Call the BroadcastMove method on the MultiplayerMicroservice microservice
        /// <see cref="Beamable.Microservices.MultiplayerMicroservice.BroadcastMove"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Common.Unit> BroadcastMove(string channelName, System.Collections.Generic.List<long> playersToNotify, Beamable.Common.TicTacToe.MoveEvent moveEvent)
        {
            object raw_channelName = channelName;
            object raw_playersToNotify = playersToNotify;
            object raw_moveEvent = moveEvent;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("channelName", raw_channelName);
            serializedFields.Add("playersToNotify", raw_playersToNotify);
            serializedFields.Add("moveEvent", raw_moveEvent);
            return this.Request<Beamable.Common.Unit>("MultiplayerMicroservice", "BroadcastMove", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersMultiplayerMicroserviceClient
    {
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_String : MicroserviceClientDataWrapper<string>
        {
        }
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_Collections_Generic_List_System_Int64 : MicroserviceClientDataWrapper<System.Collections.Generic.List<long>>
        {
        }
        
        [System.SerializableAttribute()]
        internal sealed class ParameterBeamable_Common_TicTacToe_MoveEvent : MicroserviceClientDataWrapper<Beamable.Common.TicTacToe.MoveEvent>
        {
        }
    }
    
    [BeamContextSystemAttribute()]
    public static class ExtensionsForMultiplayerMicroserviceClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute()]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            builder.AddScoped<MultiplayerMicroserviceClient>();
        }
        
        public static MultiplayerMicroserviceClient MultiplayerMicroservice(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<MultiplayerMicroserviceClient>();
        }
    }
}
